# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Modular Speakers
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  High Fidelity - Plug and Play - Long Lasting
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://modularspeakers.me" # the base hostname & protocol for your site

# Social media profiles - feel free to add more here
twitter_username: _conorpp
github_username:  conorpp
#instagram_username: beyonce
#stackoverflow_url: https://
#googleplus_username: BobMarley
#skype_username: echo123
#linkedin_url: https://

# Address information
address_street: 
address_city: Laurel
address_state: MD
address_zip: 20723

# Build settings
markdown: kramdown

sass:
    style: compressed
